### ISSUE TITLE
Support for SMART App Launch STU2

### ISSUE THREAD

**Issue by plynchnlm** [smart-on-fhir/smart-dev-sandbox#32]
Does this sandbox have support for version 2 of http://hl7.org/fhir/smart-app-launch/index.html?  How about the copy running at https://launch.smarthealthit.org/?

**Comment by vlad-ignatov** [comment]
Not yet. This is work in progress. For V2 support you can try https://smart-launcher-staging.herokuapp.com/, as well as https://smart.argo.run/

**Comment by plynchnlm** [comment]
Thanks!
