### ISSUE TITLE
SMART App Launcher Breaks Sample Patient Browser

### ISSUE THREAD

**Issue by nathanielparke** [smart-on-fhir/smart-dev-sandbox#4]
Error Description:
When using the SMART App Launcher, if you select the 'Patient Standalone Launch' as the Launch type and then click the dropdown to select patients, the browser opens the patient browser view in a new window but shows a error in the search field.

![screen shot 2018-07-20 at 10 59 14 am](https://user-images.githubusercontent.com/5566646/43017708-f813d466-8c0b-11e8-92bd-d26907e53c0e.png)

The accompanying error:
```patient-browser_1  | 172.18.0.1 - - [20/Jul/2018:17:50:49 +0000] "GET /index.html?_=1532109049022 HTTP/1.1" 200 919 "http://localhost:4001/?auth_error=&fhir_version_1=r2&fhir_version_2=r2&iss=&launch_pt=1&launch_url=&patient=&prov_skip_auth=1&provider=&pt_skip_auth=1&public_key=&sb=&sde=&token_lifetime=15&user_pt=" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1.2 Safari/605.1.15" "-"
patient-browser_1  | 2018/07/20 17:50:49 [error] 9#9: *1 open() "/usr/share/nginx/html/config/default.json5" failed (2: No such file or directory), client: 172.18.0.1, server: localhost, request: "GET /config/default.json5?_=1532109049132 HTTP/1.1", host: "localhost:4005", referrer: "http://localhost:4005/index.html?_=1532109049022"
patient-browser_1  | 172.18.0.1 - - [20/Jul/2018:17:50:49 +0000] "GET /config/default.json5?_=1532109049132 HTTP/1.1" 404 170 "http://localhost:4005/index.html?_=1532109049022" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1.2 Safari/605.1.15" "-"
smart-launcher_1   | _http_outgoing.js:647
smart-launcher_1   |     throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'first argument',
smart-launcher_1   |     ^
smart-launcher_1   |
smart-launcher_1   | TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string or Buffer
smart-launcher_1   |     at write_ (_http_outgoing.js:647:11)
smart-launcher_1   |     at ClientRequest.write (_http_outgoing.js:622:10)
smart-launcher_1   |     at Request.write (/app/node_modules/request/request.js:1501:27)
smart-launcher_1   |     at end (/app/node_modules/request/request.js:546:18)
smart-launcher_1   |     at Immediate.<anonymous> (/app/node_modules/request/request.js:575:7)
smart-launcher_1   |     at runCallback (timers.js:763:18)
smart-launcher_1   |     at tryOnImmediate (timers.js:734:5)
smart-launcher_1   |     at processImmediate (timers.js:716:5)
smart-dev-sandbox_smart-launcher_1 exited with code 1
patient-browser_1  | 172.18.0.1 - - [20/Jul/2018:17:50:52 +0000] "GET /index.html?config=stu3-local HTTP/1.1" 200 919 "http://localhost:4000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1.2 Safari/605.1.15" "-"
patient-browser_1  | 172.18.0.1 - - [20/Jul/2018:17:50:52 +0000] "GET /config/stu3-local.json5?_=1532108452138 HTTP/1.1" 200 89780 "http://localhost:4005/index.html?config=stu3-local" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1.2 Safari/605.1.15" "-"
patient-browser_1  | 172.18.0.1 - - [20/Jul/2018:17:50:52 +0000] "GET /config/stu3-local.json5?_=1532109052152 HTTP/1.1" 200 89780 "http://localhost:4005/index.html?config=stu3-local" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1.2 Safari/605.1.15" "-" 
```

System Specs:
JVM memory (Xmx): 800.0MB
CPUs Allocated to Docker: 3 
Memory Allocated to Docker: 3.0 GiB
Swap Memory Allocated to Docker: 1.0 GiB
Host OS: MacOS High Sierra
Docker Version: 18.03.1-ce-mac65 (24312)
Compose Version: 1.21.1

Steps to Reproduce Error:
Run the default settings with `docker-compose up` and visit `localhost:4001` and select the 'Patient Standalone Launch' as the launch option. Then click the patient drop down and a window will pop up that looks like the screenshot above.

Note:
After a clean restart of the server, (i.e. `Ctrl + C` and `docker-compose up`) if I visit the patient browser from `localhost:4000` then selecting `Browse Sample Patients` from either STU2 or STU3 the database loads, and is not corrupted. After following the steps in the 'Reproduce the Error' section, visiting the 'Browse Patients' page from `localhost:4000` errors out in the same way as the screenshot above. It seems to me like the App Launcher is somehow corrupting the database accesses.

**Comment by vlad-ignatov** [comment]
Thank you for reporting this! It is now fixed. Please pull the latest changes from this git repository and also update your `smartonfhir/smart-launcher` image. I would recommend deleting the old one with
 `docker image rm smartonfhir/smart-launcher` (might have to remove some stopped container first).
Then just start the project as usual: `docker-compose up`.
