### ISSUE TITLE
patient browser missing default.json5 configuration

### ISSUE THREAD

**Issue by existential360** [smart-on-fhir/smart-dev-sandbox#8]
I ran docker-compose and everything was set up correctly. When I navigated to the patient browser I see the following

![image](https://user-images.githubusercontent.com/1086489/52054075-9abf7100-255b-11e9-9bf7-686f8c8e34f5.png)

In my chrome console logs I'm seeing the following

![image](https://user-images.githubusercontent.com/1086489/52054115-b9256c80-255b-11e9-809c-91fcf266b841.png)

It seems like it can't find some config file on the first call and afterwards it times out on the patient search call. 

This is where the config file should be but it's not.

![image](https://user-images.githubusercontent.com/1086489/52056354-4c61a080-2562-11e9-8052-f4ea8224de1c.png)

 **Any help would be appreciated since this is the first time I do something with FHIR.** 

Below is my complete docker-compose up output as well. 

PS C:\Users\hsera\Desktop\stacks\smart-dev-sandbox> docker-compose up
Creating network "smart-dev-sandbox_default" with the default driver
Pulling stu3 (smartonfhir/hapi:r3-empty)...
r3-empty: Pulling from smartonfhir/hapi
5040bd298390: Pull complete
fce5728aad85: Pull complete
76610ec20bf5: Pull complete
60170fec2151: Pull complete
e98f73de8f0d: Pull complete
11f7af24ed9c: Pull complete
49e2d6393f32: Pull complete
bb9cdec9c7f3: Pull complete
b2e7db13804e: Pull complete
Pulling stu2 (smartonfhir/hapi:r2-empty)...
r2-empty: Pulling from smartonfhir/hapi
5040bd298390: Already exists
fce5728aad85: Already exists
76610ec20bf5: Already exists
60170fec2151: Already exists
e98f73de8f0d: Already exists
11f7af24ed9c: Already exists
49e2d6393f32: Already exists
bb9cdec9c7f3: Already exists
354f1ddab78b: Pull complete
Pulling patient-browser (smartonfhir/patient-browser:node)...
node: Pulling from smartonfhir/patient-browser
2a72cbf407d6: Pull complete
fefa2faca81f: Pull complete
080aeede8114: Pull complete
451a369f3693: Pull complete
ff19e3ba44c9: Pull complete
a143b8e5deb8: Pull complete
8c5b87628899: Pull complete
2918c1567995: Pull complete
0b1d2cb11d86: Pull complete
191a4147e0a4: Pull complete
Pulling fhir-viewer (smartonfhir/fhir-viewer:)...
latest: Pulling from smartonfhir/fhir-viewer
ff3a5c916c92: Pull complete
b430473be128: Pull complete
7d4e05a01906: Pull complete
8aeac9a3205f: Pull complete
437cb7b0509b: Pull complete
Pulling smart-launcher (smartonfhir/smart-launcher:)...
latest: Pulling from smartonfhir/smart-launcher
3d77ce4481b1: Pull complete
c8d9ca1153eb: Pull complete
7d024d87fd15: Pull complete
59a13018a3af: Pull complete
9a0a45c8d5ab: Pull complete
69fb6314ce8c: Pull complete
5f12d719065d: Pull complete
c8c2e29bfe54: Pull complete
efa89c090cd5: Pull complete
993e82541f7e: Pull complete
4b61733b2da1: Pull complete
1f63b4322a05: Pull complete
766ba72c8b14: Pull complete
Pulling index (nginx:alpine)...
alpine: Pulling from library/nginx
169185f82c45: Pull complete
c8d54ad152f5: Pull complete
59470ef7a01b: Pull complete
193bacda595b: Pull complete
Creating smart-dev-sandbox_fhir-viewer_1     ... done
Creating smart-dev-sandbox_patient-browser_1 ... done
Creating smart-dev-sandbox_stu2_1            ... done
Creating smart-dev-sandbox_index_1           ... done
Creating smart-dev-sandbox_stu3_1            ... done
Creating smart-dev-sandbox_smart-launcher_1  ... done
Attaching to smart-dev-sandbox_stu2_1, smart-dev-sandbox_fhir-viewer_1, smart-dev-sandbox_patient-browser_1, smart-dev-sandbox_index_1, smart-dev-sandbox_stu3_1, smart-dev-sandbox_smart-launcher_1
stu2_1             | ------------------------------------------------------------
stu2_1             | 🔥 HAPI FHIR 3.2.0 - Command Line Tool
stu2_1             | ------------------------------------------------------------
stu2_1             | Max configured JVM memory (Xmx): 800.0MB
stu2_1             | Detected Java version: 1.8.0_111
stu2_1             | ------------------------------------------------------------
stu2_1             | 12:50:34 INFO  ca.uhn.fhir.cli.RunServerCommand - Server is configured to allow external references
stu2_1             | 12:50:34 INFO  ca.uhn.fhir.cli.RunServerCommand - Server is configured to not enforce referential integrity
stu2_1             | 12:50:34 INFO  ca.uhn.fhir.context.FhirContext - Creating new FHIR context for FHIR version [DSTU2]
stu2_1             | 12:50:34 INFO  ca.uhn.fhir.cli.RunServerCommand - Preparing HAPI FHIR JPA server on port 4002
stu2_1             | 12:50:34 INFO  ca.uhn.fhir.cli.RunServerCommand - Starting HAPI FHIR JPA server in DSTU2 mode
stu3_1             | ------------------------------------------------------------
stu3_1             | 🔥 HAPI FHIR 3.2.0 - Command Line Tool
stu3_1             | ------------------------------------------------------------
stu3_1             | Max configured JVM memory (Xmx): 800.0MB
stu3_1             | Detected Java version: 1.8.0_111
stu3_1             | ------------------------------------------------------------
stu3_1             | 12:50:34 INFO  ca.uhn.fhir.cli.RunServerCommand - Server is configured to allow external references
stu3_1             | 12:50:34 INFO  ca.uhn.fhir.cli.RunServerCommand - Server is configured to not enforce referential integrity
stu3_1             | 12:50:34 INFO  ca.uhn.fhir.context.FhirContext - Creating new FHIR context for FHIR version [DSTU3]
stu3_1             | 12:50:34 INFO  ca.uhn.fhir.cli.RunServerCommand - Preparing HAPI FHIR JPA server on port 4003
stu3_1             | 12:50:35 INFO  ca.uhn.fhir.cli.RunServerCommand - Starting HAPI FHIR JPA server in DSTU3 mode
smart-launcher_1   | SMART launcher listening on port 80!
stu2_1             | 12:50:45 INFO  ca.uhn.fhir.context.FhirContext - Creating new FHIR context for FHIR version [DSTU2]
stu2_1             | 12:50:46 INFO  ca.uhn.fhir.context.FhirContext - Creating new FHIR context for FHIR version [DSTU2_HL7ORG]
stu3_1             | 12:50:46 INFO  ca.uhn.fhir.context.FhirContext - Creating new FHIR context for FHIR version [DSTU3]
stu2_1             | 12:50:51 WARN  o.h.e.jdbc.spi.SqlExceptionHelper - SQL Warning Code: 10000, SQLState: 01J01
stu2_1             | 12:50:51 WARN  o.h.e.jdbc.spi.SqlExceptionHelper - Database 'directory:target/jpaserver_derby_files' not created, connection made to existing database instead.
stu2_1             | 12:50:51 WARN  o.h.e.jdbc.spi.SqlExceptionHelper - SQL Warning Code: 10000, SQLState: 01J01
stu2_1             | 12:50:51 WARN  o.h.e.jdbc.spi.SqlExceptionHelper - Database 'directory:target/jpaserver_derby_files' not created, connection made to existing database instead.
stu2_1             | 12:50:52 INFO  ca.uhn.fhir.cli.RunServerCommand - Server started on port 4002
stu2_1             | 12:50:52 INFO  ca.uhn.fhir.cli.RunServerCommand - Web Testing UI : http://localhost:4002/
stu2_1             | 12:50:52 INFO  ca.uhn.fhir.cli.RunServerCommand - Server Base URL: http://localhost:4002/baseDstu2/
stu3_1             | 12:50:54 WARN  o.h.e.jdbc.spi.SqlExceptionHelper - SQL Warning Code: 10000, SQLState: 01J01
stu3_1             | 12:50:54 WARN  o.h.e.jdbc.spi.SqlExceptionHelper - Database 'directory:target/jpaserver_derby_files' not created, connection made to existing database instead.
stu3_1             | 12:50:54 WARN  o.h.e.jdbc.spi.SqlExceptionHelper - SQL Warning Code: 10000, SQLState: 01J01
stu3_1             | 12:50:54 WARN  o.h.e.jdbc.spi.SqlExceptionHelper - Database 'directory:target/jpaserver_derby_files' not created, connection made to existing database instead.
stu3_1             | 12:50:54 INFO  ca.uhn.fhir.cli.RunServerCommand - Server started on port 4003
stu3_1             | 12:50:54 INFO  ca.uhn.fhir.cli.RunServerCommand - Web Testing UI : http://localhost:4003/
stu3_1             | 12:50:54 INFO  ca.uhn.fhir.cli.RunServerCommand - Server Base URL: http://localhost:4003/baseDstu3/
patient-browser_1  | 172.18.0.1 - - [31/Jan/2019:12:54:52 +0000] "GET /config/default.json5?_=1548939292074 HTTP/1.1" 404 572 "http://localhost:4005/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36" "-"
patient-browser_1  | 2019/01/31 12:54:52 [error] 9#9: *1 open() "/usr/share/nginx/html/config/default.json5" failed (2: No such file or directory), client: 172.18.0.1, server: localhost, request: "GET /config/default.json5?_=1548939292074 HTTP/1.1", host: "localhost:4005", referrer: "http://localhost:4005/"

**Comment by vlad-ignatov** [comment]
You shouldn't be opening the patient browser directly. Please use the `Browse Sample Patients` links in the home page (http://localhost:4000/) instead.

The patient browser accepts a `config` URL parameter that tells it which server to connect to. The possible values in this case are `dstu2-local` and `stu3-local`. The value of this parameter defaults to `default` which makes sense for the online version (http://patient-browser.smarthealthit.org/)  but there is no default server in the local setup.
