### ISSUE TITLE
Connecting to designated HAPI FHIR server

### ISSUE THREAD

**Issue by JosephAnder** [smart-on-fhir/smart-dev-sandbox#9]
We're trying to add the smart launcher and its tools into our environment. We have our own FHIR servers already up and running. I wanted to know how we could configure the image to hook up in the same way the local servers do. I'm wondering if it would be easier to grab the smart launcher project instead of this sandbox?

**Comment by vlad-ignatov** [comment]
Both options should be doable. Considering that this is designed to provide an "all in one" type of experience, I would probably do the second one (fork the launcher).

The launcher is just a NodeJS proxy server that sits in front of any open FHIR server. For example, in our case we have an open HAPI server at https://r3.smarthealthit.org and the launcher makes that accessible through https://launch.smarthealthit.org/v/r3/fhir.

It should be just a matter of configuration which is controlled with environment variables. You take a look at https://github.com/smart-on-fhir/smart-dev-sandbox/blob/master/docker-compose.yml#L7-L20 to see how the launcher is configured. Enabling the patient picker might be tricky, but I can help you with that, once you get there.

**Comment by JosephAnder** [comment]
I figured it might be easier to fork the launcher, thank you for the help!
